### ISSUE TITLE
Exhibit subtitle isn't visible in masthead

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2258]
Related to the Blacklight 7 / Bootstrap 4 upgrade (I assume). 

If you provide a subtitle for the exhibit it doesn't display in the masthead:

<img width="1216" alt="Screen Shot 2019-11-12 at 3 55 04 PM" src="https://user-images.githubusercontent.com/101482/68717988-51c62f80-0565-11ea-8155-cfd4ee417db1.png">

This appears to be due to this selector:

```css
.d-none, .masthead small {
  display: none !important;
}
```
If I disable the `display: none;` in both occurrences, the subtitle appears as expected.
